#!/usr/bin/env bash
#PBS -l nodes=1:ppn=8,walltime=48:00:00

module load Fiji-ImageJ/20161104
/opt/compsci/Fiji-ImageJ/20161104/ImageJ-linux64
--headless -macro /hpcdata/sms/GlomerularIdentification/ImageData/LDHBTrichrome
'dir1=/hpcdata/sms/GlomerularIdentification/ImageData/LDHBTrichrome/Images
 dir2=/hpcdata/sms/GlomerularIdentification/ImageData/LDHBTrichrome/Fibrosis' 
